language: generic

sudo: required

services: 
 - docker

before_install: 
 - docker build -t rtest -f ./client/Dockerfile.dev  ./client

script: 
 - sudo docker run -e CI=true rtest npm run test


after_success: 
 - sudo docker build -t xlr99/multi-client ./client
 - sudo docker build -t xlr99/multi-nginx ./nginx  
 - sudo docker build -t xlr99/multi-worker ./worker
 - sudo docker build -t xlr99/multi-server ./server

#Logging into docker hub
 - sudo echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin  

#Pushing the images to docker hub

 - sudo docker push xlr99/multi-client
 - sudo docker push xlr99/multi-nginx
 - sudo docker push xlr99/multi-worker
 - sudo docker push xlr99/multi-server

