language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t rtest -f ./client/Dockerfile.dev  ./client

script:
  - sudo docker run -e CI=true rtest npm run test


after_success:
  - sudo docker build -t multi-client ./client
  - sudo docker build -t multi-nginx ./nginx  
  - sudo docker build -t multi-worker ./worker
  - sudo docker build -t multi-server ./server

#Logging into docker hub
- sudo echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin  

#Pushing the images to docker hub

- docker push multi-client
- docker push multi-nginx
- docker push multi-worker
- docker push multi-server
